version: "3"
#Docker port 3000, server port 8001
services:
  with-docker-multi-env-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: with-docker-multi-env-production
    ports:
      - "8001:3000"
